// Code generated by "stringer -type OpCode,ErrCode -output codes_string.go"; DO NOT EDIT.

package tftp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpRRQ-1]
	_ = x[OpWRQ-2]
	_ = x[OpDATA-3]
	_ = x[OpACK-4]
	_ = x[OpERROR-5]
	_ = x[OpOACK-6]
}

const _OpCode_name = "OpRRQOpWRQOpDATAOpACKOpERROROpOACK"

var _OpCode_index = [...]uint8{0, 5, 10, 16, 21, 28, 34}

func (i OpCode) String() string {
	i -= 1
	if i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUndefined-0]
	_ = x[ErrFileNotFound-1]
	_ = x[ErrAccessViolation-2]
	_ = x[ErrDiskFull-3]
	_ = x[ErrIllegalOp-4]
	_ = x[ErrUnknownTID-5]
	_ = x[ErrFileExists-6]
	_ = x[ErrNoSuchUser-7]
}

const _ErrCode_name = "ErrUndefinedErrFileNotFoundErrAccessViolationErrDiskFullErrIllegalOpErrUnknownTIDErrFileExistsErrNoSuchUser"

var _ErrCode_index = [...]uint8{0, 12, 27, 45, 56, 68, 81, 94, 107}

func (i ErrCode) String() string {
	if i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
