// Code generated by "stringer -type OpCode,ErrCode -output codes_string.go"; DO NOT EDIT.

package tftp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opRRQ-1]
	_ = x[opWRQ-2]
	_ = x[opDATA-3]
	_ = x[opACK-4]
	_ = x[opERROR-5]
	_ = x[opOACK-6]
}

const _OpCode_name = "OpRRQOpWRQOpDATAOpACKOpERROROpOACK"

var _OpCode_index = [...]uint8{0, 5, 10, 16, 21, 28, 34}

func (i opCode) String() string {
	i -= 1
	if i >= opCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errUndefined-0]
	_ = x[errFileNotFound-1]
	_ = x[errAccessViolation-2]
	_ = x[errDiskFull-3]
	_ = x[errIllegalOp-4]
	_ = x[errUnknownTID-5]
	_ = x[errFileExists-6]
	_ = x[errNoSuchUser-7]
}

const _ErrCode_name = "ErrUndefinedErrFileNotFoundErrAccessViolationErrDiskFullErrIllegalOpErrUnknownTIDErrFileExistsErrNoSuchUser"

var _ErrCode_index = [...]uint8{0, 12, 27, 45, 56, 68, 81, 94, 107}

func (i errCode) String() string {
	if i >= errCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
